spring.application.name=forum

# Dados do banco de dados
spring.datasource.url=jdbc:postgresql://localhost:5432/forumhub
spring.datasource.username=postgres
spring.datasource.password=${bookstore}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate / JPA# Hibernate / JPA
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

